name: agroaurora-env
dependencies:
  - python=3.9
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - keras
      - tensorflow
      - pytz
      - arrow
      - requests
      - joblib
      - matplotlib
      - azureml-inference-server-http

